version: '3.8'

services:
    app_laravel:
        build:
            context: .
        container_name: app_laravel
        image: app_laravel:latest
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel

    app_nginx:
        image: nginx:latest
        container_name: app_nginx
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app_laravel
        networks:
            - laravel

    app_mysql:
        container_name: app_mysql
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3308}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
